FROM node:lts AS builder
COPY . /src
WORKDIR /src
RUN npm install
RUN npm run build

FROM node:lts-alpine
COPY --from=builder /src/dist /app/dist
COPY package*.json /app/
WORKDIR /app
RUN ls -ahl
RUN npm install --production
CMD ["npm", "run", "start:prod"]
