version: "3"

volumes:
  influx:
  grafana:

services:
  validator-revenue:
    build: .
    command: npm run start:dev
    volumes:
      - .:/src
      - ./validators.json:/config/validators.json
    env_file: .env

  influx:
    image: influxdb:alpine
    volumes:
      - influx:/var/lib/influxdb

  grafana:
    image: grafana/grafana:7.3.6
    volumes:
      - grafana:/var/lib/grafana
    ports:
      - 127.0.0.1:3001:3000
