version: "3"

services:
  validator-revenue:
    build: .
    command: npm run start:dev
    volumes:
      - .:/src
      - ./validators.json:/config/validators.json
    env_file: .env

  influx:
    image: influxdb:alpine
    volumes:
      - ./influx_data:/var/lib/influxdb