{
 "title": "Validator Revenue",
 "description": "Example for https://github.com/eiabea/validator_revenue",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "validator",
    "label": "Validator",
    "query": "SHOW TAG VALUES ON etherstaker2 FROM performance WITH KEY = \"validator\""
   }
  ]
 },
 "panels": [
  {
   "title": "Stakers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "alias": "$tag_staker",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "staker" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "stakers",
     "select": [
      [
       { "params": [ "dollar" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Multi Validator", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Performance",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "1d",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "performance",
     "query": "SELECT mean(\"perf1d\")  / 1000000000 FROM \"performance\" WHERE (\"validator\" = '12087') AND $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "perf1d" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "validator", "operator": "=~", "value": "/^$validator$/" }
     ]
    },
    {
     "alias": "7d",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "performance",
     "select": [
      [
       { "params": [ "perf7d" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "validator", "operator": "=~", "value": "/^$validator$/" }
     ]
    },
    {
     "alias": "31d",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "performance",
     "select": [
      [
       { "params": [ "perf31d" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "validator", "operator": "=~", "value": "/^$validator$/" }
     ]
    },
    {
     "alias": "365d",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "performance",
     "query": "SELECT mean(\"perf365d\")  / 1000000000 FROM \"performance\" WHERE $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "perf365d" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "validator", "operator": "=~", "value": "/^$validator$/" }
     ]
    },
    {
     "alias": "price",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "performance",
     "query": "SELECT last(\"price\") FROM \"performance\" WHERE (\"validator\" =~ /^$validator$/) AND $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "price" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "validator", "operator": "=~", "value": "/^$validator$/" }
     ]
    },
    {
     "alias": "revenue",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "performance",
     "query": "SELECT last(\"price\") * (last(\"perf365d\") / 1000000000) FROM \"performance\" WHERE (\"validator\" =~ /^$validator$/) AND $timeFilter GROUP BY time($__interval)  fill(previous)",
     "select": [
      [
       { "params": [ "price" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Revenue",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "performance",
     "query": "SELECT last(\"price\") * (last(\"perf365d\") / 1000000000) FROM \"performance\" WHERE (\"validator\" =~ /^$validator$/) AND $timeFilter GROUP BY time($__interval)  fill(previous)\n",
     "select": [
      [
       { "params": [ "perf365d" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current ETH Price",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "performance",
     "select": [
      [
       { "params": [ "price" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "validator", "operator": "=~", "value": "/^$validator$/" }
     ]
    }
   ]
  },
  { "title": "Single Validator", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Performance",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "1d",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "performance",
     "query": "SELECT mean(\"perf1d\")  / 1000000000 FROM \"performance\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "perf1d" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1000000000" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "7d",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "performance",
     "select": [
      [
       { "params": [ "perf7d" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1000000000" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "31d",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "performance",
     "select": [
      [
       { "params": [ "perf31d" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1000000000" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "365d",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "performance",
     "query": "SELECT mean(\"perf365d\")  / 1000000000 FROM \"performance\" WHERE $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "perf365d" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1000000000" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "price",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "performance",
     "query": "SELECT mean(\"price\") FROM \"performance\" WHERE $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "price" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "revenue",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "performance",
     "query": "SELECT last(\"price\") * (last(\"perf365d\") / 1000000000) FROM \"performance\" WHERE $timeFilter GROUP BY time($__interval)  fill(previous)",
     "select": [
      [
       { "params": [ "price" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Revenue",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "performance",
     "query": "SELECT last(\"price\") * (last(\"perf365d\") / 1000000000) FROM \"performance\" WHERE $timeFilter GROUP BY time($__interval)  fill(previous)\n",
     "select": [
      [
       { "params": [ "perf365d" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current ETH Price",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "performance",
     "select": [
      [
       { "params": [ "price" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  }
 ]
}